development:
  adapter: postgresql
  encoding: unicode
  database: debatable_development
  pool: 5
  username: bradpuder
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: debatable_test
  pool: 5
  username: bradpuder
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: debatable_production
  pool: 5
  username: bradpuder
  password:
