development:
  adapter: postgresql
  encoding: unicode
  database: debatable_development
  pool: 5
  username: postgres
  password: a

test:
  adapter: postgresql
  encoding: unicode
  database: debatable_test
  pool: 5
  username: postgres
  password: a

production:
  adapter: postgresql
  encoding: unicode
  database: debatable_production
  pool: 5
  username: postgres
  password: a
